### ISSUE TITLE
Can you crop the text into more lines

### ISSUE THREAD

**Issue by LaAlwino123** [boghammar/MMM-CrisisInformationSweden#11]
I have a issue that the text is just one single line that covers whole screen. Do someone know how to fix it?

**Comment by ChrisAcrobat** [comment]
You can write some custom css. Do you want to know how?

**Comment by LaAlwino123** [comment]
Yes, can someone give me a tutorial please?

**Comment by ChrisAcrobat** [comment]
How much CSS knowledge do you have? Can you upload a photo on how it looks now?

**Comment by ChrisAcrobat** [comment]
How familiar are you with CSS? You could try adding and playing around with the CSS below.
```CSS
.MMM-CrisisInformationSweden .module-content>div {
        width: 50%;
}
```
Add it to the file `MagicMirror/css/custom.css`.
